config/routes.rb
Rabel::Application.routes.draw do
  root 'welcome#index'
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  patch 'users/update_account' => 'users#update_account', :as => :update_account
  patch 'users/update_password' => 'users#update_password', :as => :update_password
  patch 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 'go/:key' => 'nodes#show', :as => :go
  get 't/:id' => 'topics#show', :as => :t
  get '/topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get 'my/topics' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'

  resources :nodes do
    resources :topics do
      member do
        get :move
        get :edit_title
        patch :update_title
      end
    end
  end
  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    patch :toggle_comments_closed
    patch :toggle_sticky
    get :new_from_home, :on => :collection
    post :create_from_home, :on => :collection
  end

  resources :comments, :bookmarks, :upyun_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do
    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :nodes do
      post :sort, :on => :collection
      get :move, :on => :member
      patch :move_to, :on => :member
    end

    resources :users do
      member do
        patch :toggle_admin
        patch :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards

    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root 'welcome_admin#index'
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Notifiable
  include Rabel::ActiveCache

  DEFAULT_HIT = 0
  default_value_for :hit, DEFAULT_HIT
  default_value_for :content, ''
  default_value_for :involved_at do
    Time.zone.now
  end

  belongs_to :node, :touch => true, :counter_cache => true
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :bookmarks, :as => :bookmarkable, :dependent => :destroy
  has_many :notifications, :as => :notifiable, :dependent => :destroy

  validates :node_id, :user_id, :title, :presence => true

  after_create :send_notifications

  def last_comment
    self.comments.order('created_at ASC').last
  end

  def locked?
    Time.now - self.created_at > Siteconf.topic_editable_period
  end

  def allow_modification_by?(user)
    (!locked? && self.user == user) || user.can_manage_site?
  end

  def notifiable_title
    title
  end

  def notifiable_path
    "/t/#{id}"
  end

  def self.sticky_topics
    ts = select('updated_at').with_sticky(true).order('updated_at DESC').first.try(:updated_at)
    return Rabel::Model::EMPTY_DATASET unless ts.present?
    count = with_sticky(true).count
    Rails.cache.fetch("topics/sticky/#{ts}-#{count}") do
      with_sticky(true).order('updated_at DESC').all
    end
  end

  def self.home_topics(num)
    ts = select('updated_at').order('updated_at DESC').first.try(:updated_at)
    return Rabel::Model::EMPTY_DATASET unless ts.present?
    node_ts = Node.select('updated_at').order('updated_at DESC').first.try(:updated_at)
    Rails.cache.fetch("topics/homepage/#{self.count}/#{num}-#{ts}/#{node_ts}") do
      excluded_nodes = Node.where(:quiet => true).pluck(:id)
      if excluded_nodes.any?
        where("node_id NOT in (?)", excluded_nodes).with_sticky(false).latest_involved_topics(num)
      else
        with_sticky(false).latest_involved_topics(num)
      end
    end
  end

  def self.with_sticky(sticky)
    where(:sticky => sticky)
  end

  def self.latest_involved_topics(num)
    order('involved_at DESC').limit(num).all
  end

  def self.recent_topics(num)
    ts = select('updated_at').order('updated_at DESC').first.try(:updated_at)
    return Rabel::Model::EMPTY_DATASET unless ts.present?
    Rails.cache.fetch("topics/recent/#{self.count}/#{num}-#{ts}") do
      order('involved_at DESC').limit(num).all
    end
  end

  def mention_check_text
    self.title + self.content
  end

  def mentioned_users
    mentioned_names = self.mention_check_text.scan(Notifiable::MENTION_REGEXP).collect {|matched| matched.first}.uniq
    mentioned_names.delete(self.user.nickname)
    mentioned_names.map { |name| User.find_by_nickname(name) }.compact
  end

  def prev_topic(node)
    node.topics.where(['id < ?', self.id]).order('created_at DESC').first
  end

  def next_topic(node)
    node.topics.where(['id > ?', self.id]).order('created_at ASC').first
  end

  private

    def send_notifications
      mentioned_users.each do |user|
        Notification.notify(
          user,
          self,
          self.user,
          Notification::ACTION_TOPIC,
          self.content
        )
      end
    end

end

app/controllers/admin/topics_controller.rb
# encoding: utf-8
class Admin::TopicsController < Admin::BaseController
  def index
    @topics = Topic.order('created_at DESC').page(params[:page])
    @title = '讨论话题'
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      redirect_to admin_topics_path
    else
      redirect_to admin_root_path
    end
  end
end

app/controllers/topics_controller.rb
# encoding: utf-8
class TopicsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_node, :except => [:show, :index, :preview, :toggle_comments_closed, :toggle_sticky, :new_from_home, :create_from_home]
  before_filter :find_topic_and_auth, :only => [:edit_title,:update_title,
    :edit, :update, :move, :destroy]
  before_filter :only => [:toggle_comments_closed, :toggle_sticky] do |c|
    auth_admin
  end

  def index
    respond_to do |format|
      format.html {
        per_page = Siteconf::HOMEPAGE_TOPICS
        @title = '全站最新更改记录'
        if params[:page].present?
          current_page = params[:page].to_i
          @title += " (第 #{current_page} 页)"
        else
          current_page = 1
        end

        @topics = Topic.cached_pagination(current_page, per_page, 'updated_at')

        @canonical_path = topics_path
        @canonical_path += "?page=#{current_page}" if current_page > 1

        @seo_description = @title
      }
      format.atom {
        @feed_items = Topic.recent_topics(Siteconf::HOMEPAGE_TOPICS)
        @last_update = @feed_items.first.updated_at unless @feed_items.empty?
        render :layout => false
      }
    end
  end

  def show
    raise ActiveRecord::RecordNotFound.new if params[:id].to_i.to_s != params[:id]

    @topic = Topic.find_cached(params[:id])
    store_location

    Topic.increment_counter(:hit, @topic.id)

    @title = @topic.title
    @node = @topic.cached_assoc_object(:node)

    @total_comments = @topic.comments_count
    @total_pages = (@total_comments * 1.0 / Siteconf.pagination_comments.to_i).ceil
    @current_page = params[:p].nil? ? @total_pages : params[:p].to_i
    @per_page = Siteconf.pagination_comments.to_i
    @comments = @topic.cached_assoc_pagination(:comments, @current_page, @per_page, 'created_at', Rabel::Model::ORDER_ASC)

    @new_comment = @topic.comments.new
    @total_bookmarks = @topic.bookmarks.count

    @canonical_path = "/t/#{params[:id]}"
    @canonical_path += "?p=#{@current_page}" if @total_pages > 1
    @seo_description = "#{@node.name} - #{@topic.user.nickname} - #{@topic.title}"

    @prev_topic = @topic.prev_topic(@node)
    @next_topic = @topic.next_topic(@node)

    respond_to do |format|
      format.html
    end
  end

  def new
    @topic = @node.topics.new

    respond_to do |format|
      format.html
    end
  end

  def new_from_home
    @topic = Topic.new
  end

  def create
    @topic = @node.topics.new(topic_params)
    @topic.user = current_user
    if @topic.save
      redirect_to t_path(@topic.id)
    else
      render :new
    end
  end

  def create_from_home
    @node = Node.find(params[:topic][:node_id])
    @topic = @node.topics.new(topic_params)
    @topic.user = current_user

    if @topic.save
      redirect_to t_path(@topic.id)
    else
      render :new_from_home
    end
  end

  def edit_title
    respond_to do |f|
      f.js
    end
  end

  def update_title
    respond_to do |f|
      f.js {
        unless @topic.update_attributes(topic_params)
          render :text => :error, :status => :unprocessable_entity
        end
      }
    end
  end

  def edit
  end

  def update
    if params[:new_node_id].present?
      # move to new node
      @new_node = Node.find(params[:new_node_id])
      respond_to do |format|
        format.js {
          if @new_node.present?
            @topic.node = @new_node
            if @topic.save
              render :js => "window.location.reload()"
            else
              render :js => "$.facebox('移动帖子失败')"
            end
          else
            render :js => "$.facebox('节点不存在')"
          end
        }
      end
    else
      if @topic.update_attributes(topic_params)
        redirect_to t_path(@topic.id)
      else
        flash[:error] = '之前的更新有误，请编辑后再提交'
        render :edit
      end
    end
  end

  def move
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @topic.destroy
      redirect_to root_path, :notice => '帖子删除成功'
    else
      raise RuntimeError.new('删除帖子出错')
    end
  end

  def preview
    @type = ['topic', 'comment', 'page'].delete params[:type]
    respond_to do |f|
      if @type.present?
        f.text { @content = params[:content] }
      else
        render :text => :error, :status => :unprocessable_entity
      end
    end
  end

  def toggle_comments_closed
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:comments_closed)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  def toggle_sticky
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:sticky)
    @topic.touch
    redirect_to t_path(@topic.id)
  end

  private
    def find_node
      @node = Node.find(params[:node_id])
    end

    def find_topic_and_auth
      @topic = @node.topics.find(params[:id])
      authorize! :update, @topic, :message => '你没有权限管理此主题'
    end

    def topic_params
      params.require(:topic).permit(:title, :content)
    end
end

app/views/topics/show/_bookmark_button.html.haml
- if user_signed_in?
  .inner
    .fr{:align => :right}
      - if current_user.bookmarked?(@topic)
        = link_to '取消收藏', current_user.bookmark_of(@topic), :method => :delete, :class => 'op cancel'
      - else
        = link_to '加入收藏', topic_bookmarks_path(@topic), :method => :post, :class => :op
    &nbsp;&nbsp;

app/views/topics/show/_bookmarked_users.html.haml
- if @total_bookmarks > 0
  - content_for :rightbar do
    .box
      .box-header
        收藏此话题的成员
      .inner
        - @topic.bookmarks.each do |b|
          = user_profile_avatar_link(b.user, :mini)

app/views/topics/show/_comment_form.html.haml
- if user_signed_in?
  = form_for [@topic, @new_comment] do |f|
    .box
      .box-header
        .fr
          ⬆
          = link_to '回到顶部', 'javascript:void(0);', :class => 'dark back_to_top'
        现在就添加一条回复
      .inner
        = render 'shared/fileupload_widget', :textarea_selector => "textarea#comment_content"
        = render 'shared/preview_widget', :ref => :comment_content, :type => :comment
        = f.text_area :content, :rows => 5, :style => 'width: 98%;'
        .sep10
        = f.submit '发送', :class => 'btn btn-sm btn-success', :data => {:disable_with => t('tips.submitting')}
        %small.gray 支持 Ctrl + Enter 快捷键

app/views/topics/show/_comments.html.haml
%section
  .box
    .box-header
      .fr
        - if @topic.comments_closed?
          回复权限关闭
        - else
          ⬇
          = link_to '跳到回复', 'javascript:void(0);', :class => 'dark jump_to_comment'
      = "#{@total_comments} 回复"
    #replies{:class => "#{'fix_cell' if @total_pages == 1}"}
      = render @comments
    .center
      = paginate @comments, :param_name => :p

app/views/topics/show/_manage.html.haml
- if can? :update, @topic
  - content_for :rightbar do
    .box
      .box-header
        话题管理
      .cell
        = link_to '修改标题', edit_title_node_topic_path(@node, @topic), :remote => true, :class => :btn
        = link_to '编辑全部', edit_node_topic_path(@node, @topic), :class => :btn
      .cell
        = link_to '移动到新节点', move_node_topic_path(@node, @topic), :remote => true, :class => :btn
      - if current_user.can_manage_site?
        .cell
          - toggle_comments_closed_tip = @topic.comments_closed? ? '允许回复' : '禁止回复'
          = link_to toggle_comments_closed_tip, topic_toggle_comments_closed_path(@topic), :method => :patch, :class => :btn
          - toggle_sticky_tip = @topic.sticky? ? '取消置顶' : '置顶此话题'
          = link_to toggle_sticky_tip, topic_toggle_sticky_path(@topic), :method => :patch, :class => :btn
      .inner
        = link_to '删除此话题', node_topic_path(@node, @topic), :method => :delete, :data => {:confirm => t(:delete_confirm)}, :class => 'btn btn-sm btn-danger'